# -*- coding: utf-8 -*-
"""data_visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11llfZdaxKw0-VUH1QzymUyHhvdN5gQfG
"""

import pandas as pd
import numpy as np

# Load your previous clean unemployment data
df_unemployment = pd.read_csv('dublin_unemployment_CLEAN.csv')

# Create a mock 'Property Market' dataset to start our Business Analysis
# In a real scenario, we would download this, but let's build the structure first
np.random.seed(42)
districts = ['Dublin 1', 'Dublin 2', 'Dublin 4', 'Dublin 8', 'Dublin 15', 'Dublin 24']
data_size = 500

property_data = {
    'Transaction_Date': pd.to_datetime(np.random.choice(pd.date_range('2024-01-01', '2025-12-31'), data_size)),
    'District': np.random.choice(districts, data_size),
    'Sale_Price': np.random.randint(250000, 950000, data_size),
    'Property_Type': np.random.choice(['Second-Hand', 'New-Build'], data_size)
}

df_property = pd.DataFrame(property_data)
df_property.to_csv('dublin_property_prices_2026.csv', index=False)
print("Business Dataset Created: ready for Advanced SQL linking.")

import pandas as pd

# Load the data
df = pd.read_csv('dublin_property_prices_2026.csv')

# Ensure you are using 'Sale_Price' and 'District'
table_data = df[['Transaction_Date', 'District', 'Sale_Price']]
print(table_data.head())

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Load the data
df = pd.read_csv('dublin_investment_analysis_results.csv')

# 2. Fix: Check the column names automatically to avoid the ValueError
print("Current Columns in your file:", df.columns.tolist())

# Use a professional style
sns.set_theme(style="whitegrid")

# --- IMAGE 1: THE RISK HEATMAP ---
plt.figure(figsize=(12, 6))
# Sort so the safest (lowest score) is at the top
df_sorted = df.sort_values('Investment_Risk_Score')
colors = sns.color_palette("RdYlGn_r", len(df_sorted))
ax1 = sns.barplot(x='Investment_Risk_Score', y='District', data=df_sorted, palette=colors)
plt.title('Investment Risk Score by District (Lower is Safer)', fontsize=15, pad=20)
plt.savefig('1_investment_risk_heatmap.png', bbox_inches='tight')
plt.show()

# --- IMAGE 2: PRICE VS. JOB RISK (Updated Column Name) ---
plt.figure(figsize=(10, 6))
# CHANGED 'Unemployment_Rate' to 'Job_Risk_Factor'
sns.scatterplot(x='Job_Risk_Factor', y='Avg_Price', hue='District', size='Investment_Risk_Score', sizes=(100, 500), data=df)
plt.title('Property Price vs. Job Risk Correlation', fontsize=15)
plt.xlabel('Job Risk Factor (Unemployment %)')
plt.ylabel('Average Sale Price (€)')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.savefig('2_price_unemployment_correlation.png', bbox_inches='tight')
plt.show()

# --- IMAGE 3: QUARTERLY TRENDS ---
plt.figure(figsize=(12, 6))
df_trend = df.sort_values('Quarter')
sns.lineplot(x='Quarter', y='Avg_Price', hue='District', marker='o', data=df_trend)
plt.title('District Price Volatility Over Time', fontsize=15)
plt.savefig('3_quarterly_price_trends.png', bbox_inches='tight')
plt.show()

plt.figure(figsize=(8, 8))
risk_summary = df.groupby('District')['Investment_Risk_Score'].mean().sort_values()
plt.pie(risk_summary, labels=risk_summary.index, autopct='%1.1f%%', colors=sns.color_palette("viridis"), startangle=140)
plt.title('Average Risk Weighting by District', fontsize=15)
plt.savefig('4_risk_distribution_pie.png', bbox_inches='tight')
plt.close()
print("Graphs successfully generated using 'Job_Risk_Factor'!")

